runtime: nodejs18

handlers:
  # Rute untuk menyajikan file statis seperti CSS, JS, gambar, dll.
  # Mencari file di dalam folder 'dist'.
  - url: /(.*\.(json|ico|js|css|png|jpg|svg))$
    static_files: dist/\1      # <-- DIUBAH DARI 'build'
    upload: dist/(.*\.(json|ico|js|css|png|jpg|svg))$ # <-- DIUBAH DARI 'build'

  # Rute fallback untuk semua path lainnya (PENTING untuk React Router)
  # App Engine akan menyajikan file index.html utama untuk setiap request
  # yang tidak cocok di atas, agar React bisa mengambil alih routing.
  - url: /.*
    static_files: dist/index.html # <-- DIUBAH DARI 'build'
    upload: dist/index.html     # <-- DIUBAH DARI 'build'